-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 01:09:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webProject` DEFAULT CHARACTER SET utf8 ;
USE `webProject` ;

-- -----------------------------------------------------
-- Table `webProject`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webProject`.`Player` (
  `playerID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(500) NULL,
  `Total points` INT NULL,
  PRIMARY KEY (`playerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webProject`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webProject`.`Categories` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(45) NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webProject`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webProject`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `Score` INT NULL,
  `Player_playerID` INT NOT NULL,
  `Categories_CategoryID` INT NOT NULL,
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_Player_idx` (`Player_playerID` ASC) VISIBLE,
  INDEX `fk_Game_Categories1_idx` (`Categories_CategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Player`
    FOREIGN KEY (`Player_playerID`)
    REFERENCES `webProject`.`Player` (`playerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_Categories1`
    FOREIGN KEY (`Categories_CategoryID`)
    REFERENCES `webProject`.`Categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
